# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='closing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='opening_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
